Models/ErrorViewModel.cs
using System;

namespace ProjectOne.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TipListModel.cs
using System.Collections;
using System.Collections.Generic;

public class TripListModel
{
    public List<Trip> Trips { get; set; }

}

Models/Trip.cs
using System;

public class Trip
{
    public int TripId { get; set; }
    public string Destination { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public string Accomodation { get; set; }
    public string AccomodationPhone { get; set; }
    public string AccomodationEmail { get; set; }
    public string ThingToDo1{ get; set; }
    public string ThingToDo2 { get; set; }
    public string ThingToDo3 { get; set; }

}

Models/TripContext.cs
using Microsoft.EntityFrameworkCore;

namespace ProjectOne.Models
{
    public class TripContext : DbContext
    {
        public TripContext(DbContextOptions<TripContext> options)
            : base(options)
        {
            ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
        }

        public DbSet<Trip> Trips { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectOne.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectOne.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TripContext _context;

        public HomeController(ILogger<HomeController> logger, TripContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new TripListModel
            {
                Trips = new List<Trip>()
            };

            //TODO: Get all Trips from the Database
            var trips = _context.Trips.ToList();

            //Assign each trip to the list of Trips in TripListModel
           
            foreach(var trip in trips)
            {
                model.Trips.Add(trip);
            }

            return View(model);
        }

        public IActionResult Clear()
        {
            TempData.Clear();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TripController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectOne.Models;
using System;
using System.Runtime.InteropServices;


namespace ProjectOne.Controllers
{
    public class TripController : Controller
    {
       private  readonly ILogger<TripController> _logger;
        private TripContext _context;
        public TripController(ILogger<TripController> logger, TripContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Add()
        {
            return View(new Trip());
        }



        [HttpPost]
        public IActionResult Add(Trip model)
        {
            var destination = model.Destination;
            var accomodation = model.Accomodation;

            //TODO: Save the model data to TempDate
            TempData["TripId"] = model.TripId;
            TempData["Accomodation"] = accomodation;
            TempData["StartDate"] = model.StartDate;
            TempData["EndDate"] = model.EndDate;
            TempData["Destination"] = destination;
            TempData["AccomodationPhone"] = model.AccomodationPhone;
            TempData["AccomodationEmail"] = model.AccomodationEmail;
            TempData["ThingToDo1"] = model.ThingToDo1;
            TempData["ThingToDo2"] = model.ThingToDo2;
            TempData["ThingToDo3"] = model.ThingToDo3;

            ViewBag.Destination = destination;
            ViewBag.Accomdation = accomodation;

            //TODO: Redirect to Add Step 2
            if (!string.IsNullOrEmpty(model.Accomodation))
            {
                return View("Add2", model);
            }

            return View("Add3", model);
        }
        [HttpPost]
        public IActionResult Add2(Trip model)
        {
            TempData["AccomodationPhone"] = model.AccomodationPhone;
            TempData["AccomodationEmail"] = model.AccomodationEmail;
            return View("Add3", model);
        }

        [HttpPost]
        public IActionResult Save(Trip model)
        {
            model.AccomodationPhone = (string)TempData["AccomodationPhone"];
            model.AccomodationEmail = (string)TempData["AccomodationEmail"];
            model.Accomodation = (string)TempData["Accomodation"];
            model.StartDate = (DateTime)TempData["StartDate"];
            model.EndDate = (DateTime)TempData["EndDate"];
            model.Destination = (string)TempData["Destination"];
          
            _context.Add(model);
            _context.SaveChanges();
            TempData["SuccessMessage"] = $"Trip to {model.Destination} added";
            return Redirect("/Home/Index");
        }
    }
}

Views/Home/Index.cshtml
@model TripListModel
@{
    ViewData["Title"] = "Home Page";
    var successMessage = (string)TempData["SuccessMessage"];
}
<header>
    <h1>My Trip Log</h1>
</header>
<body>
     @if(!string.IsNullOrEmpty(successMessage))
     {
        <p>@successMessage</p>
     };


    <a href="@Url.Action("Add", "Trip")">Add Trip</a>
    <div class="inform">
        <table>
            <tr>
                <th>Destination</th>
                <th>Accomodations</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Things To Do</th>

            </tr>


            @foreach (var trip in Model.Trips)
            {
                <tr>
                    <td>@trip.Destination</td>
                    <td>@trip.Accomodation</td>
                    <td>@trip.StartDate.ToShortDateString()</td>
                    <td>@trip.EndDate.ToShortDateString()</td>
                    <td>@trip.ThingToDo1<br />@trip.ThingToDo2<br />@trip.ThingToDo3</td>

                </tr>
            }

        </table>
    </div>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -My Trip Log</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Trip/Add.cshtml
@model Trip
@{
    ViewData["Title"] = "Add";

    var accomodation = TempData["Accomodation"];
}
<header>
    <h1>My Trip Log</h1>
</header>
<h1>Add Trip Destination and Dates</h1>
<form action="@Url.Action("Add", "Trip")" method="post">
    <label for="Destination">Destination:</label><br>
    <input type="text" id="Destination" name="Destination"><br>

    <label for="Accomodations">Accomodations:</label><br>
    <input type="text" id="Accomodations" name="Accomodation"><br>

    <label for="StartDate">Start Date:</label><br>
    <input type="datetime" id="StartDate" name="StartDate"><br>

    <label for="EndDate">EndDate:</label><br>
    <input type="datetime" id="EndDate" name="EndDate"><br>
    <button class="btn-outline-primary" type="submit">Next</button>
   

</form>
<a class="btn btn-outline-primary" href="@Url.Action("Clear", "Home")">Cancel</a>

Views/Trip/Add2.cshtml
@model Trip
@{
    ViewData["Title"] = "Add2";
}
<header>
    <h1>My Trip Log</h1>
</header>
<h1>Add Info for @Model.Accomodation</h1>
<form action="@Url.Action("Add2", "Trip")" method="post">
    @Html.HiddenFor(m => m.Destination)
    <label for="AccomodationPhone">PhoneNumber:</label><br>
    <input type="text" id="AccomodationPhone" name="AccomodationPhone"><br>

    <label for="AccomodationEmail">Email Address:</label><br>
    <input type="text" id="AccomodationEmail" name="AccomodationEmail"><br>

    <button class="btn-outline-primary" type="submit">Next</button>


</form>
<a class="btn" href="@Url.Action("Clear", "Home")">Cancel</a>

Views/Trip/Add3.cshtml
@model Trip
@{
    ViewData["Title"] = "Add3";
}
<header>
    <h1>My Trip Log</h1>
</header>
<h1>Add things to do in @Model.Destination</h1>
<form action="@Url.Action("Save", "Trip")" method="post">
    <label for="ThingToDo1"></label><br>
    <input type="text" id="ThingToDo1" name="ThingToDo1"><br>

    <label for="ThingToDo2"></label><br>
    <input type="text" id="ThingToDo2" name="ThingToDo2"><br>

    <label for="ThingToDo3"></label><br>
    <input type="text" id="ThingToDo3" name="ThingToDo3"><br>

    <button class="btn-outline-primary" type="submit">Save</button>
    
</form>
<a class="btn" href="@Url.Action("Clear", "Home")">Cancel</a>